apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 18000
  selector:
    app: envoy
