kind: Pod
apiVersion: v1
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  volumes:
    - name: manifest-data
      configMap:
        name: manifest-config
    - name: envoy-data
      emptyDir: {}
  containers:
    - name: envoy
      image: docker.io/envoyproxy/envoy:v1.17-latest
      ports:
        - name: http
          containerPort: 18000
          protocol: TCP
      resources: { }
      volumeMounts:
        - name: envoy-data
          mountPath: /etc/envoy
  initContainers:
    - name: envoy-init
      image: docker.io/kettil/test-envoy-init-container:latest
      env:
        - name: MANIFEST_FILE
          value: /etc/faas/manifest.yaml
        - name: ENVOY_CONFIG_FILE
          value: /etc/envoy/envoy.yaml
      volumeMounts:
        - name: manifest-data
          mountPath: /etc/faas
        - name: envoy-data
          mountPath: /etc/envoy
